defaults:
  - _self_
  - task: FactoryTaskPegHoleInsertionGPT #FactoryTaskPegHoleInsertionGPT #FactoryTaskNutBoltPickGPT #FactoryTaskNutBoltPickGPT  
  - train: ${task}PPO
  - hydra/job_logging: disabled
  - override hydra/launcher:  local
  - override hydra/output:  local
# python  ./isaacgymenvs/isaacgymenvs/train.py
is_transfor: False #True #
#adapt-params
is_adapt_w: False  #True 

similarity_threshold: 0.2  
is_soft_attention: False
adapt_fps :  20 

# model_gpt: gpt-3.5-turbo #-16k #-0613  #gpt-3.5-turbo-16k-0613 #gpt-4-0314  # LLM model (other options are gpt-4, gpt-4-0613, gpt-3.5-turbo-16k-0613)
# gpt_key: 'sk-B1vr45pdGzgYmdayA85d910a4b1e48CaA646AfA8365401F0'  #"sk-jE0I4dUNGl4drntw957f725080Ec4cB69d17389728C9508f"  #sk-B1vr45pdGzgYmdayA85d910a4b1e48CaA646AfA8365401F0
# gpt_url: "https://gtapi.xiaoerchaoren.com:8932/v1" #https://gtapi.xiaoerchaoren.com:8932

model_gpt: gpt-4-0613 #gpt-4-0613 #0314  
gpt_key: "sk-mdIi7O0RoLWufmEq02C4B5E7699f4b07Bc8d5cFe0cA9E3B2" #"sk-XqfdalXAmY2iVurpD83f599dE60c4f8396A5Cf0119E3C084"
#sk-dFg5sMzl8RIhJhdxD224976926564401Bd0e09Cc278b928b
gpt_url: 'https://gtapi.xiaoerchaoren.com:8932/v1' #"https://api.gpts.vin/v1"

temperature: 1.0
suffix: GPT  # suffix for generated files (indicates LLM model)

# Task name - used to pick the class to load
task_name: ${task.name}
# experiment name. defaults to name of training config
experiment: ''

# env_path for custom environment
env_path: ''

# if set to positive integer, overrides the default number of environments
num_envs: ''

# seed - set to -1 to choose random seed
seed: 42
# set to True for deterministic performance
torch_deterministic: False

# set the maximum number of learning iterations to train for. overrides default per-environment setting
max_iterations: ''

## Device config
#  'physx' or 'flex'
physics_engine: 'physx'
# whether to use cpu or gpu pipeline
pipeline: 'gpu'
# device for running physics simulation
sim_device: 'cuda:0'
# device to run RL
rl_device: 'cuda:0'
graphics_device_id: 0

## PhysX arguments
num_threads: 4 # Number of worker threads per scene used by PhysX - for CPU PhysX only.
solver_type: 1 # 0: pgs, 1: tgs
num_subscenes: 4 # Splits the simulation into N physics scenes and runs each one in a separate thread

# RLGames Arguments
# test - if set, run policy in inference mode (requires setting checkpoint to load)
test: False #True 
# used to set checkpoint path
checkpoint: #'/home/jkx/桌面/project/ITN/isaacgymenvs/isaacgymenvs/checkpoints/last_FactoryTaskNutBoltPickPlacem20GPT_ep_1024.pth' #'isaacgymenvs/isaacgymenvs/outputs/train/2024-04-20_22-05-38/runs/FactoryTaskNutBoltPickPlaceGPT-2024-04-20_22-05-39/nn/last_FactoryTaskNutBoltPickPlacem20GPT_ep_1024.pth'  #'/home/jkx/桌面/project/ITN/isaacgymenvs/isaacgymenvs/checkpoints/last_FactoryTaskNutBoltPickPlaceGPT_ep.pth'
# set sigma when restoring network
sigma: ''
# set to True to use multi-gpu horovod training
multi_gpu: False

wandb_activate: False
wandb_group: ''
wandb_name: ${train.params.config.name}
# wandb_entity: ''
# wandb_project: 'isaacgymenvs'
wandb_entity: 'jma2020'
wandb_project: 'isaac_gpt'
wandb_tags: []
wandb_logcode_dir: '' 

capture_video: False
capture_video_freq: 5000
capture_video_len: 200
force_render: True  #False

# disables rendering
# headless: False
headless: False #headless=False force_render=True 

# set default task and default training config based on task
# defaults:
#   - task: Ant
#   - train: ${task}PPO
#   - hydra/job_logging: disabled

# set the directory where the output files get saved
# hydra:
#   output_subdir: null
#   run:
#     dir: .{"transfor": {"cos_sim": transfor:
